[package]
name = "fake-beet"
version = "0.1.0"
edition = "2024"
publish = false
authors.workspace = true
license.workspace = true

[dependencies]
escargot = "0.5.15"
eyre = "0.6.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[lints]
workspace = true

[[bin]]
name="fake-beet"
path="src/bin/fake_beet.rs"

[dev-dependencies]
tempfile = "3.27.0"
