[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["cargo", "derive"] }
q-filter-tree = { path = "../q-filter-tree", features = ["clap"] }
arg_split = { path = "../arg_split" }
serde_json = "1.0.64"
serde = "^1.0.100"
shared = { path = "../shared" }
walkdir = "2"
