[package]
name = "soundbox-ii"
version = "0.1.0"
edition = "2018"
description = "Interactive graph-based sequencer for beets songs playing on a VLC backend."

[workspace]
members = ["q-filter-tree", "vlc-http", "frontend", "shared"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
q-filter-tree = { path = "./q-filter-tree" }
vlc-http = { path = "./vlc-http" }
tokio = { version = "1.8.1", features = ["rt-multi-thread", "sync", "macros"] }
warp = "0.3.1"
http = "0.2.4"
clap = "2.33.3"
shared = { path = "./shared", features = ["server"] }
serde_json = "1.0.64"
futures = "^0.3"
hotwatch = "0.4.5"
chrono = "0.4.19"
