[workspace]
members = [ "arg-util", "beet-pusher", "bucket-spigot", "shared", "spigot-visual", "vlc-http", "vlc-http-auth", "vlc-http-auth-clap", "xtask" ]
resolver = "2"


[workspace.lints.clippy]
# teach me
pedantic = { level = "warn", priority = -1}
# except this confusing pattern
bool_to_int_with_if = { level = "allow", priority = 1}
# ok to ignore with no reason
ignore_without_reason = { level = "allow", priority = 1}

# no unwrap
unwrap_used = "deny"
# no panic
panic = "deny"
# document why lints are allowed on case-by-case basis
allow_attributes_without_reason = "warn"

[workspace.lints.rust]
# docs!
missing_docs = "deny"
# no unsafe
unsafe_code = "forbid"

[workspace.lints.rustdoc]
# docs!
broken_intra_doc_links = "deny"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
