[package]
name = "vlc-http-auth"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
arg_util = { version = "0.1.0", path = "../arg-util" }
base64 = "0.22.1"
http = "1.1.0"
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true
