[package]
name = "spigot-visual"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bucket-spigot = { version = "0.1.0", path = "../bucket-spigot" }
clap = "4.5.48"
eyre = "0.6.12"
tiny_http = { version = "0.12.0", default-features = false }
ts-rs = "11.0.1"
tungstenite = "0.28.0"
