[package]
name = "vlc-http-test"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
arbtest = "0.3.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1.44"
urlencoding = "2.1.3"
vlc-http = { version = "0.1.0", path = "../vlc-http" }

[lints]
workspace = true
