
# cargo-vet audits file

[[audits.bstr]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.12.1 -> 1.12.0"
notes = "Docs change and inconsequential lifetime annotation"

[[audits.humantime]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
version = "2.3.0"
notes = "Forbids unsafe, did not see any ambient capabilities used"

[[audits.idna]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.0 -> 0.4.0"
notes = "Clippy-style updates, and reworking features for std/core"

[[audits.idna_adapter]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.0 -> 1.0.0"
notes = "No unsafe, and `#![no_std]`"

[[audits.pathdiff]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
version = "0.2.3"
notes = """
No unsafe, direct port of [cited std source] with `camino` optional duplication
[cited std source]: https://github.com/rust-lang/rust/blob/e1d0de82cc40b666b88d4a6d2c9dcbc81d7ed27f/src/librustc_back/rpath.rs#L116-L158
"""

[[audits.thiserror]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.0.16 -> 2.0.18"
notes = "No changes to unsafe, no ambient capabilities used. Generated code does not appear to substantially change."

[[audits.thiserror-impl]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.0.16 -> 2.0.18"
notes = "No unsafe changes, only changing clippy allows generated and identifier for `__private`"

[[audits.version_check]]
who = "Daniel Lambert <danjl1100@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.4 -> 0.9.5"
notes = "Docs-only change"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2027-04-19"
