[package]
name = "bucket-spigot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
arbtest = "0.3.1"
insta = { version = "1.39.0", features = ["ron"] }

[lints]
workspace = true
