[package]
name = "vlc-http-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
arg_util = { version = "0.1.0", path = "../arg_util" }
ureq = { version = "2.9.7", features = ["http-crate"] }
vlc-http = { path = "../vlc-http", features = ["clap"] }
