[package]
name = "vlc-http-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
ureq = { version = "2.9.7", features = ["http-crate"] }
vlc-http = { version = "0.1.0", path = "../vlc-http", features = ["clap"] }
