[package]
name = "vlc-http"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["macros"] }
hyper = { version = "0.14.18", features = ["client", "http1", "tcp"] }
http = "0.2.4"
base64 = "0.13.0"
backoff = { version = "0.3.0", features = ["tokio"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
shared = { path = "../shared", features = ["time_now"] }
futures = "^0.3"
urlencoding = "2.1.0"
url = "2.2.2"
