[package]
name = "vlc-http"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
awc = "2.0.3"
tokio = { version = "1.8.1", features = ["rt", "sync"] }
