[package]
name = "vlc-http"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.8.1" }
form_urlencoded = "1.0.1"
hyper = { version = "0.14.11", features = ["client", "http1", "tcp"] }
http = "0.2.4"
base64 = "0.13.0"
