[package]
name = "vlc-http"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["macros"] }
hyper = { version = "0.14.23", features = ["client", "http1", "tcp"] }
http = "0.2.8"
base64 = "0.20.0"
backoff = { version = "0.3.0", features = ["tokio"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.91"
shared = { path = "../shared", features = ["time_now"] }
futures = "^0.3"
urlencoding = "2.1.2"
url = "2.3.1"
